# Generated by Django 3.2.4 on 2021-10-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kost',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thumbnail', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=200, null=True)),
                ('caption', models.TextField(null=True)),
            ],
        ),
    ]
