# Generated by Django 3.2.4 on 2021-10-05 12:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kost',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='kost',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
