# Generated by Django 3.2.4 on 2021-10-05 13:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kost', '0002_auto_20211005_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kost',
            name='caption',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
